- id: '1607462965576'
  alias: Road condition update
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /10
  condition: []
  action:
  - service: shell_command.vegagerdin
    data: {}
  mode: single
